# Generated by Django 4.2 on 2025-05-22 06:46

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='join_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
