# Generated by Django 4.2 on 2025-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='images')),
                ('subtitle', models.TextField(max_length=2500)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=130)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('googleapp', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
