# Generated by Django 4.2 on 2025-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='image',
            field=models.ImageField(default='', upload_to='image_eng'),
            preserve_default=False,
        ),
    ]
